import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Operating Agreement — PagePerfect',
  description:
    'The terms governing your use of PagePerfect. Plain English promises alongside binding legal clauses.',
}

/* ─── Two-column clause component ─── */

function Clause({
  number,
  promise,
  legal,
}: {
  number: string
  promise: React.ReactNode
  legal: React.ReactNode
}) {
  return (
    <div className="grid grid-cols-1 gap-6 border-b border-[#111111] py-10 md:grid-cols-[1fr_2fr] md:gap-12">
      <div>
        <p className="mb-2 font-mono text-[0.625rem] uppercase tracking-[0.15em] text-[#111111]/50">
          {number} — Plain English
        </p>
        <div className="font-display text-[15px] font-bold leading-snug text-[#000000]">
          {promise}
        </div>
      </div>
      <div>
        <p className="mb-2 font-mono text-[0.625rem] uppercase tracking-[0.15em] text-[#111111]/50">
          Legal Clause
        </p>
        <div className="font-body text-[15px] leading-relaxed text-[#000000]" style={{ textAlign: 'left' }}>
          {legal}
        </div>
      </div>
    </div>
  )
}

export default function TermsPage() {
  return (
    <main id="main">
      {/* Header */}
      <section className="border-b-2 border-[#111111] py-16 md:py-24">
        <div className="mx-auto max-w-7xl px-6 md:px-8">
          <p className="mb-3 font-mono text-[0.625rem] uppercase tracking-[0.15em] text-[#111111]/50">
            Legal — Effective 21 February 2026
          </p>
          <h1
            className="font-display text-h1 font-extrabold tracking-tighter text-[#111111]"
            style={{ lineHeight: 0.95 }}
          >
            Operating Agreement
          </h1>
          <div className="mt-8 border-l-4 border-[#111111] pl-6">
            <p className="font-body text-base leading-relaxed text-[#000000]">
              <strong>PagePerfect</strong> is engineered and operated by <strong>eazyaccess ltd</strong>.
              This document defines the terms under which you operate the engine and the
              obligations of both parties.
            </p>
          </div>
          <p className="mt-6 max-w-3xl font-body text-base leading-relaxed text-[#333333]">
            We do not write contracts designed to confuse. Every clause below is presented
            with a plain-English translation so you know exactly what you are agreeing to.
          </p>
        </div>
      </section>

      {/* Clauses */}
      <section className="py-12 md:py-16">
        <div className="mx-auto max-w-7xl px-6 md:px-8">
          <Clause
            number="01"
            promise={
              <>
                PagePerfect is a typesetting engine, not a publisher.<br /><br />
                You write the book. We typeset it. Your words, your copyright, your PDF.
                We claim zero ownership of your content.
              </>
            }
            legal={
              <>
                <strong>01. Service Description.</strong> PagePerfect is a browser-based document
                typesetting service that converts user-provided Markdown, plain text, or .docx
                manuscripts into professionally typeset PDF documents using the XeLaTeX engine.
                eazyaccess ltd acts solely as a technology provider and does not function as a
                publisher, distributor, or rights holder. All intellectual property rights in
                user-submitted content remain exclusively with the user. eazyaccess ltd claims
                no ownership, license, or derivative rights over any user content processed
                through the service.
              </>
            }
          />

          <Clause
            number="02"
            promise={
              <>
                You own your output. Print it, sell it, distribute it.<br /><br />
                The PDF we generate is yours. No watermark restrictions on paid tiers.
                No royalty. No attribution required.
              </>
            }
            legal={
              <>
                <strong>02. Output Ownership &amp; License.</strong> PDF files generated by
                PagePerfect are the sole property of the user who submitted the source material.
                Users may freely reproduce, distribute, sell, or sublicense their generated PDFs
                without restriction, royalty, or attribution to eazyaccess ltd. The Drafter (free)
                tier applies a visible watermark to output files; Publisher and Studio tiers produce
                unwatermarked output. Template designs and LaTeX source code remain the intellectual
                property of eazyaccess ltd but are licensed to users implicitly through the
                generated PDF output.
              </>
            }
          />

          <Clause
            number="03"
            promise={
              <>
                Three tiers. No hidden fees. No bait-and-switch.<br /><br />
                Drafter is free forever. Publisher is $9.99/month. Studio is $199 once, for life.
                Prices change only with 60 days&rsquo; notice.
              </>
            }
            legal={
              <>
                <strong>03. Pricing &amp; Payment Terms.</strong> The service operates on a
                three-tier model: Drafter (no charge), Publisher (recurring monthly subscription
                at the published rate), and Studio (one-time lifetime payment at the published
                rate). Subscription fees are billed via Stripe. Publisher subscriptions renew
                automatically unless cancelled before the renewal date. Studio access is perpetual
                and non-recurring. eazyaccess ltd may adjust pricing with no fewer than 60 calendar
                days&rsquo; written notice to affected users. Price changes do not apply
                retroactively to active Studio license holders.
              </>
            }
          />

          <Clause
            number="04"
            promise={
              <>
                Cancel any time. No cancellation fees. No retention tricks.<br /><br />
                Cancel your Publisher subscription and it runs until the end of your billing
                period. Studio is lifetime — there is nothing to cancel.
              </>
            }
            legal={
              <>
                <strong>04. Cancellation &amp; Refunds.</strong> Publisher subscribers may cancel
                at any time via their Stripe billing portal. Cancellation takes effect at the end
                of the current billing cycle; no prorated refunds are issued for partial periods.
                Studio license holders retain lifetime access and are not subject to cancellation.
                Refund requests for Studio purchases must be submitted within 14 calendar days of
                purchase to privacy@pageperfect.studio. After 14 days, Studio purchases are
                non-refundable.
              </>
            }
          />

          <Clause
            number="05"
            promise={
              <>
                Do not use PagePerfect to format illegal content.<br /><br />
                We do not read your manuscripts — but if we are legally compelled to act,
                we will. Use the tool responsibly.
              </>
            }
            legal={
              <>
                <strong>05. Acceptable Use.</strong> Users agree not to submit content that: (a)
                violates applicable laws or regulations; (b) infringes on the intellectual property
                rights of third parties; (c) contains malicious code, executable payloads, or
                deliberately malformed input designed to exploit the compilation pipeline; or (d)
                constitutes harassment, defamation, or incitement to violence. eazyaccess ltd does
                not proactively monitor content but reserves the right to suspend or terminate
                accounts upon receipt of valid legal process or credible reports of violation.
              </>
            }
          />

          <Clause
            number="06"
            promise={
              <>
                We guarantee the engine works. We do not guarantee your book will sell.<br /><br />
                PagePerfect formats text into PDFs. We are not liable for the commercial
                success or suitability of your output.
              </>
            }
            legal={
              <>
                <strong>06. Limitation of Liability.</strong> The service is provided &ldquo;as
                is&rdquo; without warranties of merchantability or fitness for a particular purpose.
                eazyaccess ltd&rsquo;s total liability for any claim arising from use of the service
                shall not exceed the total fees paid by the user in the 12 months preceding the
                claim. eazyaccess ltd is not liable for: compilation errors caused by user-provided
                LaTeX commands, font rendering differences across viewing software, or
                print-on-demand production issues outside our compilation pipeline. eazyaccess ltd
                shall not be liable for indirect, incidental, consequential, or punitive damages.
              </>
            }
          />

          <Clause
            number="07"
            promise={
              <>
                The service may go down for maintenance. We will tell you first.<br /><br />
                Scheduled maintenance is announced. Unscheduled outages are communicated
                via the status page.
              </>
            }
            legal={
              <>
                <strong>07. Service Availability.</strong> eazyaccess ltd targets high availability
                but does not guarantee uninterrupted service. Scheduled maintenance windows will
                be announced via the{' '}
                <Link href="/status" className="underline underline-offset-2 hover:text-[#FF3333]">
                  Status
                </Link>{' '}
                page with reasonable advance notice. eazyaccess ltd is not liable for service
                interruptions caused by: infrastructure provider outages (Digital Ocean, Vercel),
                third-party service failures (Stripe, PocketBase upstream), force majeure events,
                or user-side connectivity issues. Compilation timeout is set at 45 seconds; jobs
                exceeding this limit are terminated and reported to the user.
              </>
            }
          />

          <Clause
            number="08"
            promise={
              <>
                We can terminate accounts that violate these terms.<br /><br />
                We will explain why. If the violation is fixable, we give you a chance
                to fix it first.
              </>
            }
            legal={
              <>
                <strong>08. Termination.</strong> eazyaccess ltd may suspend or terminate user
                accounts for material breach of these terms. Where practicable, eazyaccess ltd
                will provide written notice and a 14-day cure period before termination. Immediate
                termination without notice is reserved for: violations of law, security breaches,
                or actions that threaten the integrity of the service infrastructure. Upon
                termination, the user&rsquo;s right to access the service ceases. Data deletion
                follows the procedures outlined in the{' '}
                <Link href="/privacy" className="underline underline-offset-2 hover:text-[#FF3333]">
                  Data &amp; Privacy
                </Link>{' '}
                policy, Section 07.
              </>
            }
          />

          <Clause
            number="09"
            promise={
              <>
                English law governs this agreement.<br /><br />
                eazyaccess ltd is a UK company. Disputes are resolved under English law.
              </>
            }
            legal={
              <>
                <strong>09. Governing Law &amp; Jurisdiction.</strong> This agreement is governed
                by the laws of England and Wales. Any dispute arising from or in connection with
                these terms shall be subject to the exclusive jurisdiction of the courts of England
                and Wales. Nothing in this clause limits the user&rsquo;s statutory consumer rights
                under applicable local law.
              </>
            }
          />

          <Clause
            number="10"
            promise={
              <>
                If we change these terms, you get 30 days&rsquo; notice.<br /><br />
                No silent updates. Material changes are emailed directly.
              </>
            }
            legal={
              <>
                <strong>10. Amendments.</strong> eazyaccess ltd reserves the right to amend these
                terms. Material changes will be communicated to all registered users via the email
                address on file no fewer than 30 calendar days before the effective date.
                Non-material changes (e.g., formatting corrections, clarifications that do not
                alter obligations) may be applied without notice. Continued use of the service
                after the effective date of a material amendment constitutes acceptance.
              </>
            }
          />
        </div>
      </section>

      {/* Footer note */}
      <section className="border-t-2 border-[#111111] py-12">
        <div className="mx-auto max-w-7xl px-6 md:px-8">
          <p className="font-mono text-[0.625rem] uppercase tracking-[0.15em] text-[#111111]/50">
            Document version 1.0 — 21 February 2026
          </p>
          <p className="mt-3 font-body text-sm leading-relaxed text-[#333333]">
            This agreement is written in plain English alongside its legal language because
            we believe informed consent requires comprehension. Questions: privacy@pageperfect.studio.
          </p>
        </div>
      </section>
    </main>
  )
}
